---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: python-test
  name: python-test
spec:
  serviceAccountName: python-test
  containers:
  - image: simbu1290/gcp-test:python-workload-amd64
    name: python-test
